### ISSUE TITLE
`create-endline-app` installing typescript dependencies in javascript projects

### ISSUE THREAD

**Issue by zeke-io** [zeke-io/endline#55]
### Which areas are effected by this? (Leave empty if unsure)

Create Endline App (create-endline-app)

### Describe the bug

When trying to create an Endline project using `create-endline-app`, it installs `typescript` and `@types/node` as dev dependencies even when rejecting the prompt  `Do you want to use typescript?`.

I may have forgotten an if condition.

### Expected behavior

It should only install Endline as dependency when creating a javascript project.

### Steps to reproduce

1. Create a project with `create-endline-app`
2. When prompted with `Do you want to use typescript?`, press `n` so it uses the javascript template
3. Wait for it to install the dependencies
4. Look for the `typescript` and `@types/node` dev dependencies in the `package.json` file

**Comment by jaas666** [comment]
Submitted PR #62

**Comment by zeke-io** [comment]
Fixed in PR https://github.com/zeke-io/endline/pull/62
